### ISSUE TITLE
Question on using this theme with blog content

### ISSUE THREAD

**Issue by 7MinSec** [crakjie/landing-page-hugo#11]
Hi there,

I really like this theme, but also have many blog articles I'd be bringing over from my existing Ghost blog.  When I put those in the "post" folder, it throws ALL the articles on the front page - making it a large page to download!  Am I able to have a "Blog" link at the top of the landing page navigation menu where users could click that and then read my blog entries, or is this theme not really designed for that?

Thanks,
Brian

**Comment by crakjie** [comment]
You nailed it, this team is not really designed for that. But you can fork this theme if you like the design et mix it with a real blog theme.

**Comment by 7MinSec** [comment]
OK thanks much!
