### ISSUE TITLE
Images in Services vertically centered.

### ISSUE THREAD

**Issue by hfoffani** [crakjie/landing-page-hugo#22]
First of all, thanks a lot for this theme! and please, apologize if this question doesn't belong here.

When each "post" has a few paragraphs, is it possible to get its image vertically centered when is placed at the side? Of course without breaking responsiveness.

What are the best practices in this case? Keep the text small for each post?

**Comment by crakjie** [comment]
You mean, when the hight of all paragraphs is higher than the hight of the image?

That been a lot of time I haven't done any CSS, but what you can do is add a exemple in the [exempleSite](https://github.com/crakjie/landing-page-hugo/tree/master/exampleSite) section and make the modification in [services file](https://github.com/crakjie/landing-page-hugo/blob/master/layouts/partials/services.html)

As you see in the service file the is twice the container description, [one](https://github.com/crakjie/landing-page-hugo/blob/master/layouts/partials/services.html#L6-L27) display the image on the right for even post and [another](https://github.com/crakjie/landing-page-hugo/blob/master/layouts/partials/services.html#L31-L52) display the image on the left for the odd post.

**Comment by hfoffani** [comment]
> You mean, when the hight of all paragraphs is higher than the hight of the image?

Yes, exactly. See http://decastex.com

> That been a lot of time I haven't done any CSS, but what you can do is add a exemple in the exempleSite section and make the modification in services file

Ugh... I guess the time in my life to deal with CSS and bootstrap has arrived.

**Comment by hfoffani** [comment]
It was easier than I thought. Thanks for pointing me where the changes were needed.
