### ISSUE TITLE
Proposal: Customizable "Pricing" section

### ISSUE THREAD

**Issue by matgnt** [crakjie/landing-page-hugo#24]
Hi all,

for my landing page I needed a "pricing" section, so I built it into the existing template and made it customizable with a data/pricing.json

Here is how it looks like at the moment:
<img width="778" alt="screen shot 2017-09-04 at 10 12 11" src="https://user-images.githubusercontent.com/198707/30035589-84048cd4-91b4-11e7-965a-3047da354cc4.png">

The input example looks like this:
```
[
    {
        "name": "Free",
        "link": "signup/free",
        "linkText": "Signup",
        "features": [
            {
                "name": "Free-Feature 1",
                "description": "My feature 1 can do..."
            },
            {
                "name": "Free-Feature 2",
                "description": "with feature 2 you can..."
            },
            {
                "name": "",
                "description": ""
            }
        ]
    },
```
You can easily add new features or more pricing columns. (The description field is not used at the moment).

It's also resizable and should work on mobile (columns will be collapsed and shown under each other.

Does it make sense to integrate it into the template?

**Comment by crakjie** [comment]
Why not.
If not pricing section exist nothing else is impacted?

**Comment by matgnt** [comment]
Great!
No, no change if users don't want to use it.
I'll update my code a little and create a pull request after the weekend.

**Comment by crakjie** [comment]
Could you add a section in the exempleSite ?

**Comment by matgnt** [comment]
Yes, I'll add example content!
