### ISSUE TITLE
exampleSite for Hugo Theme Site

### ISSUE THREAD

**Issue by bep** [crakjie/landing-page-hugo#4]
See my preview build of the Hugo theme site:

http://185.52.0.94:1313/landing-page-hugo/

(the site may go up and down)

Compare that to

http://185.52.0.94:1313/artists/

With most themes I have tried to get it up and running with the generic Hugo Basic Example (https://github.com/spf13/HugoBasicExample).

But some themes are "too custom", so that isn't possible.

So I added support for a theme having a self-contained exampleSite. In the Artist example above, see:

https://github.com/digitalcraftsman/hugo-artists-theme/tree/master/exampleSite

For landing page I have just disabled the demo for now, but I'm happy to turn it on if we can get it either up and running with the basic example, or probably better, add an exampleSite to this repo.

**Comment by crakjie** [comment]
I can't see your site example there look always down :x.
But if I understand right you want a custom content to make a "pretty" randering?

To make it's work with your projet should I create it in a particular way ? Like a specific directory ?

**Comment by bep** [comment]
Yes, in directory exampleSite, like this:

https://github.com/digitalcraftsman/hugo-artists-theme/tree/master/exampleSite

**Comment by crakjie** [comment]
Hello I have added exemple site for [hugo-base-theme](https://github.com/crakjie/hugo-base-theme) and for [landing-page-hugo](https://github.com/crakjie/landing-page-hugo).

Feel free to ask me any questions you would have.

**Comment by bep** [comment]
Could you correct the spelling of the folder (exempleSite > exampleSite)

**Comment by crakjie** [comment]
Yep sorry
